import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  containerLoading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  listImage: { width: '100%', height: 200 },
  posterContainer: { position: 'absolute', marginLeft: 4, bottom: 1 },
  posterImage: {
    width: 120,
    height: 200,
    borderTopRightRadius: 8,
    borderTopLeftRadius: 8,
  },
  buttonBack: {
    position: 'absolute',
    backgroundColor: 'white',
    padding: 8,
    paddingHorizontal: 10,
    top: 40,
    left: 20,
    borderRadius: 100,
  },
  buttonFavorite: {
    position: 'absolute',
    backgroundColor: 'white',
    padding: 8,
    top: 40,
    right: 20,
    borderRadius: 100,
  },
  buttonRating: {
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  infoMediaContainer: { marginLeft: '40%', marginTop: 12 },
  infoMediaTitle: {
    fontWeight: '700',
    fontSize: 20,
    color: '#fff',
  },
  infoMediaTime: {
    fontWeight: '400',
    fontSize: 10,
    color: '#fff',
  },
  subInfoMediaContainer: { flexDirection: 'row' },
  subInfoDirectorText: {
    fontWeight: '400',
    fontSize: 12,
    color: '#fff',
  },
  subInfoDirectorName: {
    fontWeight: '700',
    fontSize: 12,
    color: '#fff',
  },
  ratingContainer: { flexDirection: 'row', alignItems: 'center', gap: 40 },
  ratingText: {
    fontWeight: '400',
    fontSize: 30,
    color: '#E9A6A6',
    marginTop: 20,
  },
  heartContainer: { alignItems: 'center', top: 10 },
  heartText: {
    fontWeight: '400',
    fontSize: 10,
    color: '#fff',
  },
  mediaOverviewContainer: { padding: 20 },
  mediaOverviewText: {
    fontWeight: '400',
    fontSize: 14,
    color: '#fff',
    lineHeight: 20,
  },
  castingContainer: { width: 70, marginTop: 28, marginBottom: 15 },
  castingBox: {
    backgroundColor: '#9C4A8B',
    paddingVertical: 4,
    borderRadius: 16,
    alignItems: 'center',
  },
  castingBoxText: {
    fontWeight: '600',
    fontSize: 14,
    color: '#fff',
  },
  castingLine: {
    width: 25,
    backgroundColor: '#9C4A8B',
    height: 1,
    marginTop: 8,
    alignSelf: 'center',
  },
  castingContainerList: { paddingBottom: 20 },
  actorsContainer: { flexDirection: 'row', marginBottom: 12 },
  actorsImage: {
    width: 40,
    height: 40,
    borderRadius: 100,
    backgroundColor: 'white',
  },
  actorsNameContainer: { marginLeft: 20 },
  actorsRealName: { color: '#fff', fontWeight: '700', fontSize: 15 },
  actorsCharacterName: { color: '#fff', fontWeight: '400', fontSize: 10 },
  userRating: { fontWeight: '700', fontSize: 13 },
  userListContainer: {
    backgroundColor: '#C4C4C4',
    borderRadius: 20,
    width: 150,
    gap: 6,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  userListIcon: {
    padding: 5,
    paddingHorizontal: 7,
    backgroundColor: '#fff',
    borderRadius: 100,
  },
  seriesSeasonContainer: { marginTop: 24 },
  seriesSesonNotFound: { padding: 20, alignItems: 'center' },
  textWhite: { color: '#fff' },
  userListText: {
    fontWeight: '700',
    fontSize: 11,
    color: '#000',
  },
});
