import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  modal: { margin: 0, justifyContent: 'flex-end' },
  container: {
    width: '100%',
    height: 300,
    backgroundColor: '#fff',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  avaliationText: { marginTop: 24, fontWeight: 'bold', fontSize: 18 },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 22,
  },
  input: {
    borderRadius: 30,
    height: 35,
    width: 100,
    textAlign: 'center',
    fontSize: 12,
    backgroundColor: '#C4C4C459',
  },
  modalHeader: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderColor: '#BEBEBE',
    paddingVertical: 16,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitleText: {
    fontWeight: 'bold',
    fontSize: 13,
  },
  contentContainer: {
    padding: 8,
  },
  listRadio: { flexDirection: 'row', alignItems: 'center' },
  maxRatingText: { fontWeight: '600', fontSize: 18 },
  actionButtonsContainer: {
    flexDirection: 'row',
    gap: 48,
    marginTop: 40,
  },
  cancelButton: {
    width: 100,
    height: 25,
    borderWidth: 2,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: { fontWeight: 'bold', fontSize: 12 },
  confirmButton: {
    width: 100,
    height: 25,
    borderRadius: 4,
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 25,
    justifyContent: 'center',
    backgroundColor: 'black',
    marginTop: 'auto',
  },
  confirmButtonText: {
    fontWeight: 'bold',
    fontSize: 12,
    color: 'white',
  },
});
